name: Flask App Staging CI/CD

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Install pytest
        run: pip install pytest
  
      - name: Run tests
        run: pytest
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

  validate:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible" 

  run-playbook:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: [validate]
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip3 install -r Ansible/requirements.txt

      - name: write inventory to file
        env:
          INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
        run: 'echo "$INVENTORY" > inventory'
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ secrets.KNOWN_HOST }}
          if_key_exists: fail 
          
      - name: run playbook
        run: |
          ansible-playbook -i inventory Ansible/deploy.yml --extra-vars "github_sha=${{ github.sha }}" --extra-vars "weather_api_key=${{ secrets.WEATHER_API_KEY }}"
---

name: Flask App Production CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Install pytest
        run: pip install pytest
  
      - name: Run tests
        run: pytest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

  validate:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible" 

  run-playbook:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [validate]
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip3 install -r Ansible/requirements.txt
          
      - name: write inventory to file
        env:
          INVENTORY: ${{ secrets.ANSIBLE_PROD_INVENTORY }}
        run: 'echo "$INVENTORY" > inventory'
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        env: 
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOST_PROD1 }},${{ secrets.KNOWN_HOST_PROD2 }}
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ env.KNOWN_HOSTS }}
          if_key_exists: fail 
          
      - name: run playbook
        run: |
          ansible-playbook -i inventory Ansible/deploy.yml --extra-vars "github_sha=${{ github.sha }}" --extra-vars "weather_api_key=${{ secrets.WEATHER_API_KEY }}"
